version: '3'

# docker-compose build (1x only if you edit the Dockerfile or files used by it)
# docker-compose up    (everytime you start the pipeline)

# a list of all containers you intend to use
services:

  # first: SQL DB
  mongodb:          # name : also the hostname
    image: mongo    # image downloaded from DockerHub
    ports:
    - 27017:27017      

  # second: run Python
  twitter_mdb:              # name
    build: twitter_MongoDB/     # look for a Dockerfile here -> creates an image
    volumes:               # this is how we get the python program + files in:
    - ./twitter_MongoDB/:/app   # makes the twitter bot/ folder available in the container as app/
    depends_on:            # this means that the postgres container is started then the karaokebot
    - mongodb
    
